# Frontend Next.js
FROM node:20-alpine

WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm ci

# Copy app
COPY . .

# Build Next.js
RUN npm run build

# Expose port
EXPOSE 3500

# Run the app
CMD ["npm", "run", "start"]
